# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScreenUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SourceImage = QtWidgets.QLabel(self.centralwidget)
        self.SourceImage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SourceImage.setAlignment(QtCore.Qt.AlignCenter)
        self.SourceImage.setObjectName("SourceImage")
        self.gridLayout.addWidget(self.SourceImage, 0, 0, 1, 1)
        self.DisImage = QtWidgets.QLabel(self.centralwidget)
        self.DisImage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.DisImage.setAlignment(QtCore.Qt.AlignCenter)
        self.DisImage.setObjectName("DisImage")
        self.gridLayout.addWidget(self.DisImage, 0, 2, 1, 1)
        self.LoadImageOnce = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadImageOnce.sizePolicy().hasHeightForWidth())
        self.LoadImageOnce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LoadImageOnce.setFont(font)
        self.LoadImageOnce.setObjectName("LoadImageOnce")
        self.gridLayout.addWidget(self.LoadImageOnce, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SourceImage.setText(_translate("MainWindow", "Image Source"))
        self.DisImage.setText(_translate("MainWindow", "Destination"))
        self.LoadImageOnce.setText(_translate("MainWindow", "Load Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
